import { Injectable, Logger } from '@nestjs/common';
import { LlmChatOptions, LlmMessage, LlmProvider } from '../llm-provider.interface';

/**
 * Deterministic LLM stand-in so the whole app works with zero credentials.
 * Produces plausible conversational text; structured JSON is generated by
 * AiService templates, so this only needs to handle free-form chat replies.
 */
@Injectable()
export class MockLlmProvider implements LlmProvider {
  readonly name = 'mock';
  readonly available = true;
  private readonly logger = new Logger('MockLlmProvider');

  async chat(messages: LlmMessage[], _options?: LlmChatOptions): Promise<string> {
    const lastUser = [...messages].reverse().find((m) => m.role === 'user');
    const q = (lastUser?.content ?? '').toLowerCase();
    this.logger.debug(`mock chat for: "${q.slice(0, 60)}"`);

    if (q.includes('hello') || q.includes('hi ') || q.length < 4) {
      return "Hi! I'm your AI career consultant. Tell me about your interests, what you've studied, and where you'd like to be in a year — I'll map out a path for you.";
    }
    if (q.includes('roadmap') || q.includes('plan')) {
      return 'A great roadmap moves in stages: build foundations, then core skills, then projects that prove them, and finally interview readiness. Head to the Roadmap tab and generate a personalized plan — I tailor stages to your weekly hours and level.';
    }
    if (q.includes('resume') || q.includes('cv')) {
      return 'Upload your resume in the Career tab and I will score it, highlight strengths, flag gaps, and give concrete rewrite suggestions tuned to your target role.';
    }
    if (q.includes('interview')) {
      return 'I can run a mock HR, technical, or behavioral interview. I ask one question at a time, evaluate your answers, and give you a score with feedback. Start one in the Career tab.';
    }
    return "Based on what you've shared, focus on three things: pick one target role, close your two biggest skill gaps with hands-on projects, and practice interviews weekly. I've drafted recommendations and a skill-gap view for you on the right.";
  }
}
